export const resList = [
  {
    info: {
      id: "767065",
      name: "Hotel Sakthi Balaji Bhavan",
      cloudinaryImageId: "9638a01db8e5650fb2c8748a0c7e2454",
      locality: "Bus Stand",
      areaName: "Bodinayakanur",
      costForTwo: "₹260 for two",
      cuisines: ["Indian", "South Indian"],
      avgRating: 4.2,
      veg: true,
      parentId: "458052",
      avgRatingString: "4.2",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 16,
        serviceability: "SERVICEABLE",
        slaString: "15-20 mins",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/hotel-sakthi-balaji-bhavan-bus-stand-bodinayakanur-theni-767065",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "770662",
      name: "King'S Foodies",
      cloudinaryImageId: "bfcea2108aea7a98f2b370b78b2fdac0",
      locality: "Peryandava Koil Street",
      areaName: "Bodinayakanur",
      costForTwo: "₹249 for two",
      cuisines: ["South Indian", "Chinese"],
      avgRating: 4.3,
      parentId: "460188",
      avgRatingString: "4.3",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 23,
        lastMileTravel: 0.1,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/kings-foodies-peryandava-koil-street-bodinayakanur-theni-770662",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "768153",
      name: "SRI RAM MESS",
      cloudinaryImageId: "75c49a5d43681cb2406227ae82f6c781",
      locality: "Subramanaiya Kovil North Street",
      areaName: "Bodinayakanur",
      costForTwo: "₹129 for two",
      cuisines: ["South Indian", "Beverages"],
      avgRating: 4.2,
      parentId: "458682",
      avgRatingString: "4.2",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 0.4,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "0.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/sri-ram-mess-subramanaiya-kovil-north-street-bodinayakanur-theni-768153",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "767570",
      name: "FAMOUS JIGARTHANDA",
      cloudinaryImageId: "0f14752d2d18e146285207d69e412960",
      locality: "Ph Road",
      areaName: "Bodinayakanur",
      costForTwo: "₹120 for two",
      cuisines: ["Beverages"],
      avgRating: 4.5,
      veg: true,
      parentId: "9195",
      avgRatingString: "4.5",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 18,
        lastMileTravel: 0.1,
        serviceability: "SERVICEABLE",
        slaString: "15-20 mins",
        lastMileTravelString: "0.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "FREE ITEM",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/famous-jigarthanda-ph-road-bodinayakanur-theni-767570",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "771551",
      name: "Arusuvai Unavagam",
      cloudinaryImageId: "c3bc32ad3ed9515bb0bf77c419d5a429",
      locality: "P H Road",
      areaName: "Bodinayakanur",
      costForTwo: "₹200 for two",
      cuisines: ["Indian", "South Indian", "Biryani"],
      avgRating: 4,
      parentId: "241297",
      avgRatingString: "4.0",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 0.4,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹50 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/arusuvai-unavagam-p-h-road-bodinayakanur-theni-771551",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "768027",
      name: "N.Jayaguru Foods",
      cloudinaryImageId: "ed42c5d5507c03783eb4a1c8a3dc312c",
      locality: "Bodinayakkanur",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Burgers", "Snacks", "Chinese", "Beverages"],
      avgRating: 4.3,
      parentId: "460187",
      avgRatingString: "4.3",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 34,
        lastMileTravel: 0.5,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "0.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/n-jayaguru-foods-bodinayakkanur-bodinayakanur-theni-768027",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "523344",
      name: "Udaiyar Fast Food",
      cloudinaryImageId: "timnj83fljjdzjlmghjn",
      locality: "Periyandavar Koil Circle",
      areaName: "Bodinayakanur Locality",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese"],
      avgRating: 4.7,
      parentId: "312146",
      avgRatingString: "4.7",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 23,
        lastMileTravel: 0.5,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/udaiyar-fast-food-periyandavar-koil-circle-bodinayakanur-locality-theni-523344",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "768076",
      name: "Syed Gulf Mandi",
      cloudinaryImageId: "b33020eb6608b35bc925b8cf8614b418",
      locality: "Kamaraj Bazzer",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Chinese"],
      avgRating: 4.6,
      parentId: "488150",
      avgRatingString: "4.6",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 0.6,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/syed-gulf-mandi-kamaraj-bazzer-bodinayakanur-theni-768076",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "767308",
      name: "BB DESSERTS",
      cloudinaryImageId: "d70919d5b1948b28d73c2af48d4d9013",
      locality: "Renganathapuram",
      areaName: "Bodinayakanur",
      costForTwo: "₹120 for two",
      cuisines: ["Beverages", "Juices", "Ice Cream"],
      avgRating: 4.8,
      veg: true,
      parentId: "458253",
      avgRatingString: "4.8",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 1,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "1.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/bb-desserts-renganathapuram-bodinayakanur-theni-767308",
      type: "WEBLINK",
    },
  },
  {
    info: {
      id: "785218",
      name: "S R Fish Shop",
      cloudinaryImageId: "e8adaf48df9038dba89c4388da7ccb1d",
      locality: "Thangamuthamman Kovil Street",
      areaName: "Bodinayakanur",
      costForTwo: "₹149 for two",
      cuisines: ["Seafood", "Snacks"],
      avgRating: 4.4,
      parentId: "467196",
      avgRatingString: "4.4",
      totalRatingsString: "5",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 0.4,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/s-r-fish-shop-thangamuthamman-kovil-street-bodinayakanur-theni-785218",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "766384",
      name: "Lifa Hotel",
      cloudinaryImageId: "9dacd35644b95114c74b6f1611b8571c",
      locality: "Periyandavar Kovil",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "Biryani", "Chinese"],
      parentId: "457699",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 0.4,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/lifa-hotel-periyandavar-kovil-bodinayakanur-theni-766384",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "523344",
      name: "Udaiyar Fast Food",
      cloudinaryImageId: "timnj83fljjdzjlmghjn",
      locality: "Periyandavar Koil Circle",
      areaName: "Bodinayakanur Locality",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese"],
      avgRating: 4.7,
      parentId: "312146",
      avgRatingString: "4.7",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 23,
        lastMileTravel: 0.5,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/udaiyar-fast-food-periyandavar-koil-circle-bodinayakanur-locality-theni-523344",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "784936",
      name: "A1 Palamuthir Solai",
      cloudinaryImageId: "598e07bee01f95a3b783d9b6962cd7cd",
      locality: "Kamaraj Bazzar",
      areaName: "Bodinayakanur",
      costForTwo: "₹150 for two",
      cuisines: ["Beverages"],
      avgRating: 4.5,
      veg: true,
      parentId: "467027",
      avgRatingString: "4.5",
      totalRatingsString: "3",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 0.3,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.3 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "FREE ITEM",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/a1-palamuthir-solai-kamaraj-bazzar-bodinayakanur-theni-784936",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "767576",
      name: "MURUGAN COOL BAR",
      cloudinaryImageId: "0f229c9e3a42b1ffc67c6f4bcd6680b7",
      locality: "P H Road",
      areaName: "Bodinayakanur",
      costForTwo: "₹100 for two",
      cuisines: ["Juices", "Beverages"],
      avgRating: 5,
      veg: true,
      parentId: "458334",
      avgRatingString: "5.0",
      totalRatingsString: "4",
      sla: {
        deliveryTime: 22,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 21:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/murugan-cool-bar-p-h-road-bodinayakanur-theni-767576",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "775398",
      name: "Grill Arabia",
      cloudinaryImageId: "1aa2148e2a8abd14b7a21fe239685d5b",
      locality: "Krishna Nagar",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Indian"],
      avgRating: 4.3,
      parentId: "422780",
      avgRatingString: "4.3",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 28,
        lastMileTravel: 0.8,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "0.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/grill-arabia-krishna-nagar-bodinayakanur-theni-775398",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "767935",
      name: "Brownie Bakers",
      cloudinaryImageId: "80d3024589ed6aefeb518b810af4d4cd",
      locality: "Savari Complex",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Bakery"],
      avgRating: 4.5,
      veg: true,
      parentId: "50498",
      avgRatingString: "4.5",
      totalRatingsString: "7",
      sla: {
        deliveryTime: 20,
        lastMileTravel: 0.1,
        serviceability: "SERVICEABLE",
        slaString: "15-20 mins",
        lastMileTravelString: "0.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/brownie-bakers-savari-complex-bodinayakanur-theni-767935",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "768076",
      name: "Syed Gulf Mandi",
      cloudinaryImageId: "b33020eb6608b35bc925b8cf8614b418",
      locality: "Kamaraj Bazzer",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Chinese"],
      avgRating: 4.6,
      parentId: "488150",
      avgRatingString: "4.6",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 0.6,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/syed-gulf-mandi-kamaraj-bazzer-bodinayakanur-theni-768076",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "793287",
      name: "Hari Saravana Bakery And Sweets",
      cloudinaryImageId: "f72eaa010eb21fca918a5c86e27f7b30",
      locality: "Thevaram Main Road",
      areaName: "Bodinayakanur",
      costForTwo: "₹299 for two",
      cuisines: ["Beverages", "Juices", "Chinese"],
      parentId: "474476",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 27,
        lastMileTravel: 1.7,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "1.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hari-saravana-bakery-and-sweets-thevaram-main-road-bodinayakanur-theni-793287",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "767308",
      name: "BB DESSERTS",
      cloudinaryImageId: "d70919d5b1948b28d73c2af48d4d9013",
      locality: "Renganathapuram",
      areaName: "Bodinayakanur",
      costForTwo: "₹120 for two",
      cuisines: ["Beverages", "Juices", "Ice Cream"],
      avgRating: 4.8,
      veg: true,
      parentId: "458253",
      avgRatingString: "4.8",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 1,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "1.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/bb-desserts-renganathapuram-bodinayakanur-theni-767308",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "822131",
      name: "AACHI HOME FOODS",
      cloudinaryImageId: "6dba07da9999518352608726e0c92583",
      locality: "Bodinayakanur",
      areaName: "Bodinayakanur",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese", "Snacks", "Indian"],
      parentId: "490507",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 35,
        lastMileTravel: 0.7,
        serviceability: "SERVICEABLE",
        slaString: "35-40 mins",
        lastMileTravelString: "0.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-24 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/aachi-home-foods-bodinayakanur-theni-822131",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "771717",
      name: "KAVI NILA HOME FOODS",
      cloudinaryImageId: "fe2217614733f6a885bba65f6dcfcbdc",
      locality: "Nandavanam",
      areaName: "Bodinayakanur",
      costForTwo: "₹250 for two",
      cuisines: ["Indian", "Biryani"],
      parentId: "326126",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 28,
        lastMileTravel: 1.7,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "1.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextOpenTimeMessage: "Opens next at 8 am, tomorrow",
      },
      badges: {},
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/kavi-nila-home-foods-nandavanam-bodinayakanur-theni-771717",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "767554",
      name: "A Vi M Restaurant",
      cloudinaryImageId: "b33020eb6608b35bc925b8cf8614b418",
      locality: "Telephone Exchange North Street",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Chinese", "Biryani"],
      avgRating: 4.5,
      parentId: "458323",
      avgRatingString: "4.5",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 0.3,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.3 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextOpenTimeMessage: "Opens next at 12 noon, tomorrow",
      },
      badges: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/a-vi-m-restaurant-telephone-exchange-north-street-bodinayakanur-theni-767554",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "771322",
      name: "Classic Rider Cafe",
      cloudinaryImageId: "06f5c10f23e56a63ce7f6661433eaaa4",
      locality: "P H Road",
      areaName: "Bodinayakanur",
      costForTwo: "₹300 for two",
      cuisines: ["Arabian", "Fast Food", "Chinese", "Snacks"],
      avgRating: 4,
      parentId: "17511",
      avgRatingString: "4.0",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 0.6,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextOpenTimeMessage: "Opens next at 3 pm, tomorrow",
      },
      badges: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/classic-rider-cafe-p-h-road-bodinayakanur-theni-771322",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "816918",
      name: "SK BRIYANI KING",
      cloudinaryImageId: "029d63d322601ca70faaf2edda6898e5",
      locality: "Bodinayakanur",
      areaName: "Bodinayakanur",
      costForTwo: "₹250 for two",
      cuisines: ["Biryani"],
      parentId: "489843",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 25,
        lastMileTravel: 1.1,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "1.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextOpenTimeMessage: "Opens next at 11:50 am, THURSDAY",
      },
      badges: {},
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-1be47d7f-2daf-4b8f-9760-6070516a88bb",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/sk-briyani-king-bodinayakanur-theni-816918",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];
